Cw1
dvlunev/Coursework1 pull request #1
Opened 2022-11-29 17:44 UTC by dvlunev

Проверьте пожалуйста курсовую работу

2022-11-30 08:16 UTC, OlgaLugacheva requested changes

2022-11-30 08:16 UTC, OlgaLugacheva commented on src/Employee.java
> +        } else if (fullName.equals("") && (departmentNumber <= 0 || departmentNumber >= 6) && salary > 0) {
вот это валидация (и это хорошая идея), но такие методы лучше вынести в сеттер и \или конструктор. А здесь в toString должен быть просто набор полей для текстового вывода без всяких проверок

2022-11-30 08:16 UTC, OlgaLugacheva commented on src/EmployeeBook.java
> +    public final Random RANDOM = new Random();
если это не константы, то не надо использовать верхний регистр

2022-11-30 08:16 UTC, OlgaLugacheva commented on src/EmployeeBook.java
> +                /* Вопрос 2 На разборе именно этот метод показывали random.nextInt, но с 2мя параметрами,
у этого метода две реализациии

2022-11-30 08:16 UTC, OlgaLugacheva commented on src/Main.java
> +                Средняя заработная плата составляет Exception in thread "main" java.util.MissingFormatArgumentException: Format specifier '%.2f'
потому что не конкатенацие , а через запятую указывается параметр

2022-12-02 10:25 UTC, dvlunev commented
Исправил замечания

2022-12-06 06:38 UTC, merged